"""empty message

Revision ID: 85b3f717a133
Revises: c81bffc73a97
Create Date: 2025-11-03 16:54:54.981383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85b3f717a133'
down_revision = 'c81bffc73a97'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('salt')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salt', sa.VARCHAR(length=200), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
